# -*- coding: utf-8 -*-
"""BME450_FINAL_CODE.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/116-IUsXMTgvXUFvKIR_bXo4mOGJ1Mkt6
"""

# CUDA Vegetable Set WORKS Most Recent (Updated)
import torch
from torch import nn
import torch.optim as optim
import torch.nn.functional as F
from torch.utils.data import DataLoader
from torchvision import datasets, transforms
import matplotlib.pyplot as plt
import os
import glob
import random
import numpy as np
from PIL import Image
import shutil
import ollama
import scipy

# Check for CUDA
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Using device: {device}")

# Function to convert images to .jpg
def convert_images_to_jpg(directory):
    for filepath in glob.glob(directory + '/**/*', recursive=True):
        if filepath.lower().endswith(('.png', '.jpeg', '.bmp', '.tiff', '.gif')):
            img = Image.open(filepath).convert('RGB')
            new_filepath = os.path.splitext(filepath)[0] + ".jpg"
            img.save(new_filepath, "JPEG")
            os.remove(filepath)

# Dataset paths
Root_train = r"C:\Users\ethan\BME 450\data\groceries_FUTURE\train"
Root_test = r"C:\Users\ethan\BME 450\data\groceries_FUTURE\test"
Root_validation = r"C:\Users\ethan\BME 450\data\groceries_FUTURE\validation"

# Convert images
for directory in [Root_train, Root_test, Root_validation]:
    convert_images_to_jpg(directory)

# Define transformations
train_transform = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.RandomHorizontalFlip(p=0.5),
    transforms.RandomVerticalFlip(p=0.5),
    transforms.GaussianBlur(kernel_size=(5, 9), sigma=(0.1, 5)),
    transforms.RandomRotation(degrees=(30, 70)),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.5, 0.5, 0.5], std=[0.5, 0.5, 0.5])
])

valid_transform = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.5, 0.5, 0.5], std=[0.5, 0.5, 0.5])
])

# Load datasets
train_dataset = datasets.ImageFolder(root=Root_train, transform=train_transform)
test_dataset = datasets.ImageFolder(root=Root_test, transform=valid_transform)
valid_dataset = datasets.ImageFolder(root=Root_validation, transform=valid_transform)

BATCH_SIZE = 256

# Categories
categories = ['Bean', 'Broccoli', 'Cabbage', 'Carrot', 'Cauliflower', 'Cucumber', 'Potato', 'Tomato']

# Create DataLoaders
train_loader = DataLoader(train_dataset, batch_size=BATCH_SIZE, shuffle=True, num_workers=4, pin_memory=True)
valid_loader = DataLoader(valid_dataset, batch_size=BATCH_SIZE, shuffle=False, num_workers=4, pin_memory=True)
test_loader = DataLoader(test_dataset, batch_size=BATCH_SIZE, shuffle=False, num_workers=4, pin_memory=True)

# Define the CNN model
class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        self.conv1 = nn.Conv2d(3, 32, 5)
        self.conv2 = nn.Conv2d(32, 64, 5)
        self.conv3 = nn.Conv2d(64, 128, 3)
        self.conv4 = nn.Conv2d(128, 256, 5)
        self.fc1 = nn.Linear(256, 50)
        self.pool = nn.MaxPool2d(2, 2)

    def forward(self, x):
        x = self.pool(F.relu(self.conv1(x)))
        x = self.pool(F.relu(self.conv2(x)))
        x = self.pool(F.relu(self.conv3(x)))
        x = self.pool(F.relu(self.conv4(x)))
        bs, _, _, _ = x.shape
        x = F.adaptive_avg_pool2d(x, 1).reshape(bs, -1)
        x = self.fc1(x)
        return x

# Move model to GPU
model = Net().to(device)

# Training function
def train_loop(dataloader, model, loss_fn, optimizer):
    size = len(dataloader.dataset)
    model.train()
    for batch, (X, y) in enumerate(dataloader):
        X, y = X.to(device), y.to(device)
        pred = model(X)
        loss = loss_fn(pred, y)
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        if batch % 100 == 0:
            loss, current = loss.item(), (batch + 1) * len(X)
            print(f"loss: {loss:>7f}  [{current:>5d}/{size:>5d}]")

# Testing function
def test_loop(dataloader, model, loss_fn):
    size = len(dataloader.dataset)
    num_batches = len(dataloader)
    test_loss, correct = 0, 0
    model.eval()
    with torch.no_grad():
        for X, y in dataloader:
            X, y = X.to(device), y.to(device)
            pred = model(X)
            test_loss += loss_fn(pred, y).item()
            correct += (pred.argmax(1) == y).type(torch.float).sum().item()

    test_loss /= num_batches
    correct /= size
    print(f"Test Error: \n Accuracy: {(100*correct):>0.1f}%, Avg loss: {test_loss:>8f} \n")

# Training setup
loss_fn = nn.CrossEntropyLoss()
learning_rate = 1e-3
optimizer = optim.Adam(model.parameters(), lr=learning_rate)

# Track losses
train_losses = []
test_losses = []

# Training loop
epochs = 20
for t in range(epochs):
    print(f"Epoch {t+1}\n-------------------------------")

    # Run training and testing, capture printed loss manually
    model.train()
    running_loss = 0.0
    for batch, (X, y) in enumerate(train_loader):
        X, y = X.to(device), y.to(device)
        pred = model(X)
        loss = loss_fn(pred, y)
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
        running_loss += loss.item()

        if batch % 100 == 0:
            loss_val, current = loss.item(), (batch + 1) * len(X)
            print(f"loss: {loss_val:>7f}  [{current:>5d}/{len(train_loader.dataset):>5d}]")

    avg_train_loss = running_loss / len(train_loader)
    train_losses.append(avg_train_loss)

    # Test loss
    size = len(test_loader.dataset)
    num_batches = len(test_loader)
    test_loss, correct = 0, 0
    model.eval()
    with torch.no_grad():
        for X, y in test_loader:
            X, y = X.to(device), y.to(device)
            pred = model(X)
            test_loss += loss_fn(pred, y).item()
            correct += (pred.argmax(1) == y).type(torch.float).sum().item()

    avg_test_loss = test_loss / num_batches
    test_losses.append(avg_test_loss)

    accuracy = 100 * correct / size
    print(f"Test Error: \n Accuracy: {accuracy:>0.1f}%, Avg loss: {avg_test_loss:>8f} \n")

print("Done!")

# ------------------------------------------------------
# Plotting Loss Curves (Smoothed)
# ------------------------------------------------------
from scipy.interpolate import make_interp_spline

# Prepare data
epochs_range = np.arange(1, epochs + 1)
epochs_smooth = np.linspace(epochs_range.min(), epochs_range.max(), 300)

# Smooth the lines
train_spline = make_interp_spline(epochs_range, train_losses, k=3)
test_spline = make_interp_spline(epochs_range, test_losses, k=3)

train_losses_smooth = train_spline(epochs_smooth)
test_losses_smooth = test_spline(epochs_smooth)

# Create plot
plt.figure(figsize=(10, 6))
plt.plot(epochs_smooth, train_losses_smooth, label='Training Loss', color='blue')
plt.plot(epochs_smooth, test_losses_smooth, label='Test Loss', color='red')
plt.title('Training and Test Loss Over Epochs (Smoothed)', fontsize=16)
plt.xlabel('Epoch', fontsize=14)
plt.ylabel('Loss', fontsize=14)
plt.legend(fontsize=12)
plt.grid(True, linestyle='--', alpha=0.6)
plt.show()

# Visualization: random predictions on 4 images
model.eval()
random_indices = random.sample(range(len(test_dataset)), 4)
fig, axs = plt.subplots(1, 4, figsize=(16, 4))

for i, idx in enumerate(random_indices):
    image, true_label = test_dataset[idx]
    input_tensor = image.unsqueeze(0).to(device)

    with torch.no_grad():
        output = model(input_tensor)
        pred_label = output.argmax(1).item()

    img_np = image.permute(1, 2, 0).cpu().numpy()
    img_np = (img_np * 0.5) + 0.5

    axs[i].imshow(img_np)
    axs[i].set_title(f"Predicted: {categories[pred_label]}\nTrue: {categories[true_label]}")
    axs[i].axis('off')

plt.tight_layout()
plt.show()

# Save model
torch.save(model, "450_model.pth")
print("Full model saved to 450_model.pth")

# ------------------------------------------------------
# Visualization: Plotting Weight Maps of First Convolutional Layer
# ------------------------------------------------------

# Get the weights of the first conv layer
first_conv_weights = model.conv1.weight.data.clone().cpu()

# Normalize weights to [0, 1] for visualization
min_wt = first_conv_weights.min()
max_wt = first_conv_weights.max()
first_conv_weights = (first_conv_weights - min_wt) / (max_wt - min_wt)

# Plot filters
num_filters = first_conv_weights.shape[0]
cols = 8
rows = (num_filters + cols - 1) // cols

fig, axes = plt.subplots(rows, cols, figsize=(20, 8))
fig.suptitle('First Convolutional Layer Filters', fontsize=18)

for i in range(rows * cols):
    ax = axes[i // cols, i % cols]
    if i < num_filters:
        # Permute to (H, W, C) and show
        filter_img = first_conv_weights[i].permute(1, 2, 0)
        ax.imshow(filter_img)
        ax.axis('off')
    else:
        ax.remove()

plt.tight_layout()
plt.show()


# ------------------------------------------------------
# Visualization: Feature Maps for a Single Image
# ------------------------------------------------------

# Pick a random image from the test set
random_idx = random.randint(0, len(test_dataset) - 1)
image, true_label = test_dataset[random_idx]
input_tensor = image.unsqueeze(0).to(device)

# Create a hook to capture feature maps
activation_maps = {}

def hook_fn(module, input, output):
    activation_maps[module] = output

# Attach hooks to the layers you want to visualize
hooks = []
for layer in [model.conv1, model.conv2, model.conv3, model.conv4]:
    hooks.append(layer.register_forward_hook(hook_fn))

# Forward pass
model.eval()
with torch.no_grad():
    _ = model(input_tensor)

# Remove hooks
for hook in hooks:
    hook.remove()

# Now plot feature maps
for layer, activations in activation_maps.items():
    activations = activations.squeeze(0).cpu()  # remove batch dimension
    num_feature_maps = activations.shape[0]
    cols = 8
    rows = (num_feature_maps + cols - 1) // cols

    fig, axes = plt.subplots(rows, cols, figsize=(20, 8))
    fig.suptitle(f'Feature Maps after {layer.__class__.__name__}', fontsize=18)

    for idx in range(rows * cols):
        ax = axes[idx // cols, idx % cols]
        if idx < num_feature_maps:
            ax.imshow(activations[idx], cmap='viridis')
            ax.axis('off')
        else:
            ax.remove()

    plt.tight_layout()
    plt.show()

# -------------------
# New Final Section: Sort and Recipe Request
# -------------------

# Paths
test_folder = r"C:\Users\ethan\BME 450\data\groceries_FUTURE\sort"
output_base = r"C:\Users\ethan\BME 450\data\groceries_FUTURE\refrigerator"

# Reset model to eval mode
model.eval()

# Make sure output folders exist
os.makedirs(output_base, exist_ok=True)

for category in categories:
    os.makedirs(os.path.join(output_base, category), exist_ok=True)

# Step 1: Sort images into refrigerator/
for filename in os.listdir(test_folder):
    if filename.lower().endswith((".jpg", ".png")):
        img_path = os.path.join(test_folder, filename)

        # Load and preprocess image
        image = Image.open(img_path).convert("RGB")
        image_tensor = valid_transform(image).unsqueeze(0).to(device)

        # Predict
        with torch.no_grad():
            output = model(image_tensor)
            predicted_class = output.argmax(dim=1).item()

        predicted_category = categories[predicted_class]

        dest_folder = os.path.join(output_base, predicted_category)
        os.makedirs(dest_folder, exist_ok=True)

        shutil.copy(img_path, dest_folder)
        print(f"Copied {filename} to {predicted_category}/")

# Step 2: Pick a random available category and request a recipe
available_categories = [
    category for category in categories
    if os.listdir(os.path.join(output_base, category))
]

if available_categories:
    chosen_category = random.choice(available_categories)
    print(f"\nRandomly selected category: {chosen_category}")

    response = ollama.chat(
        model='llama3.2',
        messages=[
            {
                'role': 'user',
                'content': f"Find me a simple and easy recipe using {chosen_category}."
            }
        ]
    )

    recipe = response['message']['content']
    print(f"\nRecipe for {chosen_category}:\n{recipe}\n")
else:
    print("No items found in the refrigerator!")

# Clear Refrigerator
import os
import shutil

# Path to your refrigerator folder
refrigerator_path = r"C:\Users\ethan\BME 450\data\groceries_FUTURE\refrigerator"

# Clear all files inside each category
for category in os.listdir(refrigerator_path):
    category_path = os.path.join(refrigerator_path, category)

    if os.path.isdir(category_path):
        for filename in os.listdir(category_path):
            file_path = os.path.join(category_path, filename)
            try:
                if os.path.isfile(file_path) or os.path.islink(file_path):
                    os.unlink(file_path)
            except Exception as e:
                print(f'Failed to delete {file_path}. Reason: {e}')

print("Refrigerator cleared successfully!")